<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prometheus_metamodel" nsURI="http://www.example.org/prometheus_metamodel"
    nsPrefix="prometheus_metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Percept" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal_Relationship" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Step" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Physical_Object" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Logical_Object" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Functionality" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum_Type_of_Relationship">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum_Types_Attribute">
    <eLiterals name="NONE"/>
    <eLiterals name="INT" value="1"/>
    <eLiterals name="LONG" value="2"/>
    <eLiterals name="CHAR" value="3"/>
    <eLiterals name="STRING" value="4"/>
    <eLiterals name="FLOAT" value="5"/>
    <eLiterals name="DOUBLE" value="6"/>
    <eLiterals name="BOOLEAN" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum_Visibility_Attribute">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PRIVATE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum_Type_Step">
    <eLiterals name="ACTION"/>
    <eLiterals name="SCENARIO" value="1"/>
    <eLiterals name="GOAL" value="2"/>
    <eLiterals name="PERCEPT" value="3"/>
    <eLiterals name="OTHER" value="4"/>
  </eClassifiers>
</ecore:EPackage>
